# Generated by Django 5.1.3 on 2024-12-20 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_customuser_restrict_reason_advertiserhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('HARASSMENT', '괴롭힘'), ('SPAM', '스팸'), ('INAPPROPRIATE', '부적절한 콘텐츠'), ('HATE_SPEECH', '혐오 발언'), ('OTHER', '기타')], max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['reporter', 'reported_user', 'created_at'], name='common_repo_reporte_47b12b_idx')],
            },
        ),
    ]
