# Generated by Django 5.2.8 on 2025-12-02 07:05

from django.db import migrations, models
from django.db import connection


def add_privacy_fields(apps, schema_editor):
    # Add privacy_agree columns only if they do not exist (idempotent for existing DBs)
    existing_columns = {}
    with connection.cursor() as cursor:
        for table in ['common_customuser', 'common_pendinguser']:
            try:
                cols = [col.name for col in connection.introspection.get_table_description(cursor, table)]
            except Exception:
                cols = []
            existing_columns[table] = set(cols)

    CustomUser = apps.get_model('common', 'CustomUser')
    PendingUser = apps.get_model('common', 'PendingUser')

    if 'privacy_agree' not in existing_columns.get('common_customuser', set()):
        field = models.BooleanField(default=False, help_text='개인정보 처리방침에 동의했습니다.', verbose_name='개인정보 처리 동의')
        field.set_attributes_from_name('privacy_agree')
        schema_editor.add_field(CustomUser, field)

    if 'privacy_agree' not in existing_columns.get('common_pendinguser', set()):
        field = models.BooleanField(default=False)
        field.set_attributes_from_name('privacy_agree')
        schema_editor.add_field(PendingUser, field)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('common', '0003_report'),
    ]

    operations = [
        migrations.RunPython(add_privacy_fields, reverse_code=migrations.RunPython.noop),
    ]
