# Generated by Django 5.2.8 on 2025-12-02 07:08

from django.db import migrations, models, connection


def add_terms_fields(apps, schema_editor):
    existing_columns = {}
    with connection.cursor() as cursor:
        for table in ['common_customuser', 'common_pendinguser']:
            try:
                cols = [col.name for col in connection.introspection.get_table_description(cursor, table)]
            except Exception:
                cols = []
            existing_columns[table] = set(cols)

    CustomUser = apps.get_model('common', 'CustomUser')
    PendingUser = apps.get_model('common', 'PendingUser')

    if 'terms_agree' not in existing_columns.get('common_customuser', set()):
        field = models.BooleanField(default=False, help_text='이용약관에 동의했습니다.', verbose_name='이용약관 동의')
        field.set_attributes_from_name('terms_agree')
        schema_editor.add_field(CustomUser, field)

    if 'terms_agree' not in existing_columns.get('common_pendinguser', set()):
        field = models.BooleanField(default=False)
        field.set_attributes_from_name('terms_agree')
        schema_editor.add_field(PendingUser, field)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('common', '0004_customuser_privacy_agree_pendinguser_privacy_agree'),
    ]

    operations = [
        migrations.RunPython(add_terms_fields, reverse_code=migrations.RunPython.noop),
    ]
