# Generated by Django 5.2.8 on 2025-12-02 07:12

from django.db import migrations, models, connection


def add_agree_dates(apps, schema_editor):
    existing_columns = {}
    with connection.cursor() as cursor:
        for table in ['common_customuser', 'common_pendinguser']:
            try:
                cols = [col.name for col in connection.introspection.get_table_description(cursor, table)]
            except Exception:
                cols = []
            existing_columns[table] = set(cols)

    CustomUser = apps.get_model('common', 'CustomUser')
    PendingUser = apps.get_model('common', 'PendingUser')

    if 'privacy_agree_date' not in existing_columns.get('common_customuser', set()):
        field = models.DateTimeField(blank=True, null=True, verbose_name='개인정보 처리 동의 일시')
        field.set_attributes_from_name('privacy_agree_date')
        schema_editor.add_field(CustomUser, field)

    if 'terms_agree_date' not in existing_columns.get('common_customuser', set()):
        field = models.DateTimeField(blank=True, null=True, verbose_name='이용약관 동의 일시')
        field.set_attributes_from_name('terms_agree_date')
        schema_editor.add_field(CustomUser, field)

    if 'privacy_agree_date' not in existing_columns.get('common_pendinguser', set()):
        field = models.DateTimeField(blank=True, null=True)
        field.set_attributes_from_name('privacy_agree_date')
        schema_editor.add_field(PendingUser, field)

    if 'terms_agree_date' not in existing_columns.get('common_pendinguser', set()):
        field = models.DateTimeField(blank=True, null=True)
        field.set_attributes_from_name('terms_agree_date')
        schema_editor.add_field(PendingUser, field)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('common', '0005_customuser_terms_agree_pendinguser_terms_agree'),
    ]

    operations = [
        migrations.RunPython(add_agree_dates, reverse_code=migrations.RunPython.noop),
    ]
