# Generated by Django 5.2.7 on 2025-12-02 07:14

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('common', '0006_customuser_privacy_agree_date_and_more'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, reverse_code=migrations.RunPython.noop),
    ]
