# Generated by Django 5.1.3 on 2024-12-18 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='업종명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_types', to='board.category', verbose_name='관련 카테고리')),
            ],
            options={
                'verbose_name': '업종',
                'verbose_name_plural': '업종 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='필수. 150자 이내로 입력해주세요.', max_length=150, unique=True, verbose_name='닉네임')),
                ('user_id', models.CharField(help_text='필수. 로그인에 사용될 아이디를 입력해주세요.', max_length=30, unique=True, verbose_name='아이디')),
                ('email', models.EmailField(help_text='필수. 인증에 사용될 이메일을 입력해주세요.', max_length=254, unique=True, verbose_name='이메일')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='사업장 이름')),
                ('is_active', models.BooleanField(default=False, help_text='이메일 인증 후 활성화됩니다.', verbose_name='활성화')),
                ('is_staff', models.BooleanField(default=False, verbose_name='admin 접근 권한')),
                ('is_admin', models.BooleanField(default=False, verbose_name='일반 관리자 권한')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='최고 관리자 권한')),
                ('is_advertise', models.BooleanField(default=False, verbose_name='광고주 권한')),
                ('is_restricted', models.BooleanField(default=False)),
                ('restrict_end_date', models.DateTimeField(blank=True, null=True)),
                ('restrict_reason', models.TextField(blank=True, null=True, verbose_name='정지 사유')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('email_verified', models.BooleanField(default=False, verbose_name='이메일 인증됨')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='common.businesstype', verbose_name='업종')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
            },
        ),
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('user_id', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activation_token', models.CharField(max_length=150)),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.businesstype')),
            ],
            options={
                'verbose_name': '대기 중인 사용자',
                'verbose_name_plural': '대기 중인 사용자들',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, verbose_name='자기소개')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
