# Generated by Django 5.1.3 on 2024-12-19 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='restrict_reason',
        ),
        migrations.CreateModel(
            name='AdvertiserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('is_advertiser', models.BooleanField()),
                ('reason', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertiser_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRestrictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_at', models.DateTimeField(auto_now_add=True)),
                ('restriction_reason', models.TextField()),
                ('restriction_period', models.IntegerField()),
                ('unrestricted_at', models.DateTimeField(blank=True, null=True)),
                ('unrestricted_reason', models.TextField(blank=True, null=True)),
                ('restricted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restrictions_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-restricted_at'],
            },
        ),
    ]
