# Generated by Django 5.1.3 on 2024-12-22 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='order',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='down_voter',
            field=models.ManyToManyField(blank=True, related_name='question_down_voter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='up_voter',
            field=models.ManyToManyField(blank=True, related_name='question_up_voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
