# Generated by Django 5.1.3 on 2024-12-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_advertisement_order_alter_question_down_voter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='main_poster',
            field=models.BooleanField(default=False),
        ),
    ]
